# Generated by Django 4.1.5 on 2023-03-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_feed_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='is_marked',
            new_name='is_bookmark',
        ),
    ]
